/**
 * Alsality Group design tokens.
 */
export const tokens = {
  colors: {
    background: "#FFFFFF",
    foreground: "#2C2C2C",
    foregroundAlt: "#1A1A1A",
    body: "#666666",
    muted: "#F3F3F3",
    cardService: "#F3F3F3",
    cardAbout: "#F3F3F3",
    border: "#E5E5E5",
    borderStrong: "#DBDBDB",
    label: "#CCCCCC",
    cutoutNumber: "#D1D5DB",
    cutoutLabel: "#9CA3AF",
    navInactive: "#CCCCCC",
    accent: "#F7C547",
    accentGreen: "#22C55E",
    accentBlue: "#6E99C2",
    surfaceDark: "#2C2C2C",
    heroOverlay: "rgba(15, 23, 42, 0.42)",
    star: "#FBBF24",
  },
  fontFamily: {
    sans: "var(--font-inter), system-ui, sans-serif",
  },
  fontSize: {
    badge: "0.8125rem",
    body: "1rem",
    bodySm: "0.9375rem",
    serviceTitle: "1.25rem",
    sectionTitle: "clamp(1.5rem, 4.2vw, 2rem)",
    cutoutNumber: "clamp(3rem, 8vw, 4.5rem)",
    hero: "clamp(2.25rem, 6vw, 4.5rem)",
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  letterSpacing: {
    sectionTitle: "0.02em",
    brand: "0.06em",
    hero: "0.02em",
  },
  radius: {
    badge: "9999px",
    image: "2rem",
    imageLg: "2.5rem",
    hero: "2.5rem",
    heroDesktop: "3rem",
    cutout: "1.75rem",
    serviceCard: "2rem",
    aboutCard: "2rem",
  },
  spacing: {
    sectionY: "5rem",
    sectionYDesktop: "6rem",
    cardGapMobile: "1rem",
    cardGapTablet: "1.5rem",
    cardGapDesktop: "2.5rem",
    headerMb: "2rem",
    headerMbDesktop: "2rem",
    serviceCardPaddingMobile: "1.5rem",
    serviceCardPaddingDesktop: "2.5rem",
  },
  layout: {
    maxWidth: "100%",
    pagePx: "2rem",
    pagePxTablet: "clamp(2rem, 4.5vw, 3rem)",
    pagePxDesktop: "clamp(2.5rem, 6.5vw, 5.5rem)",
    navHeightMobile: "4rem",
    navHeightDesktop: "5rem",
  },
} as const;
